/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniversalAdapter } from "./UniversalAdapter";
export * as factories from "./factories";
export { UniversalAdapter__factory } from "./factories/UniversalAdapter__factory";
